from __future__ import annotations

FILTER_ROAST = "filter roast"
ESPRESSO_ROAST = "espresso roast"
OMNI_ROAST = "omni roast"
OTHER_CATEGORY = "other"
KNOWN_VARIETALS = (
    "sudan rume",
    "ruiru 11",
    "maragogype",
    "pacamara",
    "castillo",
    "caturra",
    "catuai",
    "obata",
    "pink bourbon",
    "red bourbon",
    "yellow bourbon",
    "bourbon",
    "yellow caturra",
    "typica",
    "gesha",
    "geisha",
    "sidra",
    "java",
    "laurina",
    "wush wush",
    "chiroso",
    "papayo",
    "parainema",
    "catimor",
    "sarchimor",
    "san bernardo",
    "sl28",
    "sl34",
    "batian",
    "heirloom",
    "tabi",
    "pacas",
    "villalobos",
    "villa sarchi",
    "villasarchi",
    "aji",
    "p88",
    "s795",
)

COUNTRY_MAP = {
    "colombia": "Colombia", "colombian": "Colombia",
    "ethiopia": "Ethiopia", "ethiopian": "Ethiopia",
    "kenya": "Kenya", "kenyan": "Kenya",
    "guatemala": "Guatemala", "guatemalan": "Guatemala",
    "costa rica": "Costa Rica", "costa rican": "Costa Rica",
    "panama": "Panama", "panamanian": "Panama",
    "brazil": "Brazil", "brazilian": "Brazil",
    "indonesia": "Indonesia", "indonesian": "Indonesia",
    "sumatra": "Indonesia", "sumatran": "Indonesia",
    "honduras": "Honduras", "honduran": "Honduras",
    "peru": "Peru", "peruvian": "Peru",
    "rwanda": "Rwanda", "rwandan": "Rwanda",
    "burundi": "Burundi", "burundian": "Burundi",
    "el salvador": "El Salvador", "salvadoran": "El Salvador",
    "nicaragua": "Nicaragua", "nicaraguan": "Nicaragua",
    "mexico": "Mexico", "mexican": "Mexico",
    "papua new guinea": "Papua New Guinea", "png": "Papua New Guinea",
    "yemen": "Yemen", "yemeni": "Yemen",
    "ecuador": "Ecuador", "ecuadorian": "Ecuador",
    "bolivia": "Bolivia", "bolivian": "Bolivia",
    "uganda": "Uganda", "ugandan": "Uganda",
    "tanzania": "Tanzania", "tanzanian": "Tanzania",
    "congo": "DR Congo", "drc": "DR Congo", "dr congo": "DR Congo",
    "china": "China", "chinese": "China",
    "india": "India", "indian": "India",
    "vietnam": "Vietnam", "vietnamese": "Vietnam",
    "thailand": "Thailand", "thai": "Thailand",
    "myanmar": "Myanmar",
    "timor-leste": "East Timor", "east timor": "East Timor",
}

CANONICAL_PROCESSES = (
    (r"\bwine\s+yeast\b", "Wine Yeast"),
    (r"\b(?:anaerobic\s+natural|natural\s+anaerobic)\b", "Anaerobic Natural"),
    (r"\b(?:anaerobic\s+washed|washed\s+anaerobic)\b", "Anaerobic Washed"),
    (r"\banaerobic\s+slow\s+dry\b", "Anaerobic Natural"),
    (r"\basd\s+natural\b", "Anaerobic Natural"),
    (r"\bcarbonic\s+maceration\b", "Carbonic Maceration"),
    (r"\bcarbonic\b", "Carbonic Maceration"),
    (r"\bwashed\s+double\s+ferment(?:ed)?\b", "Washed Double Fermented"),
    (r"\bdouble\s+ferment(?:ed|ation)?\b", "Double Fermented"),
    (r"\bco[-\s]?ferment(?:ed|ation|ing)?\b", "Co-Ferment"),
    (r"\bmosto\s+washed\b", "Mosto Washed"),
    (r"\badvanced\s+washed\b", "Advanced Washed"),
    (r"\bpulped\s+natural\b", "Pulped Natural"),
    (r"\bpeach\s+honey\b", "Peach Honey"),
    (r"\bstrawberry\s+honey\b", "Strawberry Honey"),
    (r"\bpassionfruit\s+honey\b", "Passionfruit Honey"),
    (r"\blychee\s+honey\b", "Lychee Honey"),
    (r"\bwatermelon\s+honey\b", "Watermelon Honey"),
    (r"\byellow\s+honey\b", "Yellow Honey"),
    (r"\bred\s+honey\b", "Red Honey"),
    (r"\bblack\s+honey\b", "Black Honey"),
    (r"\bhoney\b(?!\s*co[-\s]?ferment)", "Honey"),
    (r"\bwet\s+hulled\b", "Wet Hulled"),
    (r"\bgiling\s+basah\b", "Wet Hulled"),
    (r"\bwashed\s+patio\s+dried\b", "Washed Patio Dried"),
    (r"\bfully\s+washed\b", "Washed"),
    (r"\bwashed\b(?!\s*co[-\s]?ferment|\s*double\s*ferment|\s*patio\s*dried)", "Washed"),
    (r"\bnatural\s+decaf\b", "Natural Decaf"),
    (r"\b(?:sugar\s*cane|sugarcane)(?:\s*ea)?\s*(?:decaf\w*|process\w*|method)?\b", "Sugar Cane Decaf"),
    (r"\bswiss\s*water\s*(?:decaf\w*|process\w*|method)?\b", "Swiss Water Decaf"),
    (r"\bmountain\s*water\s*(?:decaf\w*|process\w*|method)?\b", "Mountain Water Decaf"),
    (r"\bnatural\b(?!\s*co[-\s]?ferment|\s*decaf|\s*sugar\s*cane)", "Natural"),
    (r"\baerobic\b", "Natural"),
    (r"\bdecaf\b", "Decaf"),
)

COFFEE_FLAVOUR_LEXICON = (
    "blackcurrant coulis", "lemonade ice block", "mango cheesecake", "white chocolate", "milk chocolate",
    "dark chocolate", "bittersweet chocolate", "hot chocolate", "creamy soda", "grape soda",
    "passionfruit", "turkish delight", "candy apple", "yellow sudan rume", "elderflower",
    "lemon zest", "plum jam", "poached pear", "rooibos tea", "black tea", "chamomile tea",
    "stone fruit", "tropical fruit", "tropical fruits", "red fruit", "dark fruit", "dried fruit",
    "boysenberry ice cream", "boysenberry cupcake", "vanilla syrup", "creamy nougat", "raw honey",
    "floral honey", "chocolate milk", "chocolate-milk", "vanilla custard", "buttery pastry",
    "irish whiskey", "dark currants", "vanilla malt", "soft nougat", "pineapple lumps",
    "orange jaffa", "fruity bubblegum", "myer lemon", "vanilla flower", "rockmelon",
    "cinnamon spice", "dark cocoa", "cinnamon", "molasses", "macadamia", "pistachio",
    "pomelo", "blackcurrant", "blueberry", "blueberries", "blackberry", "blackberries",
    "boysenberry", "raspberry", "raspberries", "strawberry", "strawberries", "cherry",
    "cherries", "apricot", "peach", "plum", "guava", "mango", "papaya", "cola",
    "gumball", "blossom", "florals", "floral", "jasmine", "bergamot", "lime", "lemon",
    "orange", "citrus", "mandarin", "tangelo", "grapefruit", "rhubarb", "currants",
    "caramel", "toffee", "fudge", "honey", "maple syrup", "nougat", "hazelnut",
    "almond", "walnut", "cashew", "peanut", "pecan", "cocoa", "chocolate",
    "clove", "cardamom", "nutmeg", "ginger", "star anise", "raisins", "raisin",
    "marzipan", "brown sugar", "panela", "butterscotch", "malt", "dark rum", "rum", "maple", "toasted spices",
    "dried fig", "fig", "quince", "jammy apple", "green apple", "red apple", "apple",
    "sultana", "sultanas", "redcurrant", "redcurrants", "watermelon", "golden kiwifruit", "kiwifruit", "kiwi",
    "berry jam", "black cherry", "vanilla bean", "vanilla", "cacao nibs", "cacao",
    "dark choc", "milk choc", "marshmallow", "boysenberry yogurt", "yogurt", "yoghurt",
    "rose water", "magnolia flowers", "orange blossom", "white peach", "shortbread",
    "burnt orange", "burnt caramel", "smoked cedar", "peach liqueur", "ginger snap",
    "dried berries", "wine like finish", "orange peel", "oolong tea", "peach jam", "mixed berries",
    "pineapple lollies", "honeysuckle oolong", "white muscat", "apple juice", "jujube date", "orah mandarin",
    "parmesan cheese", "purple grapes"
)

LEXICON_SORTED = sorted(COFFEE_FLAVOUR_LEXICON, key=lambda x: len(x), reverse=True)

NON_FLAVOUR_WORDS = {
    "coffee",
    "the coffee",
    "this coffee",
    "our coffee",
    "specialty coffee",
    "espresso",
    "filter",
    "beans",
    "roast",
    "batch",
    "pulping",
    "milling",
    "harvesting",
    "sorting",
    "drying",
    "fermenting",
    "full of flavour",
    "full of flavor",
    "rich, juicy, and full of flavour",
    "rich, juicy, and full of flavor",
}

